version: "3"
services:
  web:
    build: "./web"
    ports:
      - 3000:3000
    command: npm start

  svc1:
    build: "./backend/svc1"
    ports:
      - 3001:3001
    command: npm start
    environment:
      - PORT=3001

  svc2:
    build: "./backend/svc2"
    ports:
      - 3002:3002
    command: npm start
    environment:
      - PORT=3002
