apiVersion: v1
kind: Service
metadata:
  name: svc1
  namespace: default
  labels:
    app: svc1
    component: svc1
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: svc1
    component: svc1
