apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
  labels:
    app: web
    component: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: web
    component: web
