name: Hello World Cron Job Again

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  print_hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
